import math

FPS = 30

# Save Data

SAVE_NAME = 'SwordPlay'
SAVE_DATA_VERSION = 'version'
SAVE_DATA_LEADER_NAMES = 'leader-names'
SAVE_DATA_LEADER_SCORES = 'leader-scores'
SAVE_DATA_PREV_NAME = 'prev-name'

# Grid

GRID_SIZE = 5
GRID_WIDTH = 12
GRID_HEIGHT = 7
GRID_OFFSET_X = 2
GRID_OFFSET_Y = 2
GRID_MIN_PX = GRID_OFFSET_X
GRID_MAX_PX = GRID_OFFSET_X + (GRID_SIZE * GRID_WIDTH)
GRID_MID_PX = (GRID_MIN_PX + GRID_MAX_PX) // 2
GRID_MIN_PY = GRID_OFFSET_Y
GRID_MAX_PY = GRID_OFFSET_Y + (GRID_SIZE * GRID_HEIGHT)
GRID_MID_PY = (GRID_MIN_PY + GRID_MAX_PY) // 2

# Directions

DIR_U = 0
DIR_D = 1
DIR_L = 2
DIR_R = 3

# Game Objects

ENEMY_RESPAWN_OFFSET_Y = 10
ENEMY_INVINCIBILITY_FRAMES = 30

ENEMY_MONSTER_DAMAGE = 1
ENEMY_MONSTER_HIT_SIZE = 2
ENEMY_MONSTER_HP_MAX = 1
ENEMY_MONSTER_MOVE_RATE = 4
ENEMY_MONSTER_POINTS = 10

ENEMY_MUTANT_DAMAGE = 1
ENEMY_MUTANT_HIT_SIZE = 3
ENEMY_MUTANT_HP_MAX = 2
ENEMY_MUTANT_MOVE_RATE = 3
ENEMY_MUTANT_POINTS = 30
ENEMY_MUTANT_CHARGE_DIST = 20

PICKUP_FLASH_RATE = FPS // 5  # frames
PICKUP_HIT_SIZE = 3
PICKUP_HEALTH_EFFECT = 1  # hp restored
PICKUP_POINTS_EFFECT = 100  # points earned

PLAYER_MAX_HP = 3
PLAYER_HIT_SIZE = 3
PLAYER_INVINCIBILITY_FRAMES = 30

# Miscellaneous

FLASHING_TEXT_INTERVAL = FPS // 2  # frames

GAME_OVER_ANIM_SPIN_RATE = 4  # frames
GAME_OVER_ANIM_DURATION = 2 * FPS  # frames

KILLS_PER_PRIZE = 10

SWORD_DAMAGE = 1
SWORD_DISTANCE = 6.5
SWORD_LENGTH = SWORD_DISTANCE + 6
SWORD_SWING_ARC = 90  # degrees
SWORD_SWING_COLLISION_TOLERANCE = math.pi / 16  # radians
SWORD_SWING_SPEED = 300 // FPS  # degrees per frame
SCORE_DISPLAY_CAP = 999999
